name: test and deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "."
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
    outputs:
      page_url: "http://127.0.0.1:8080/"
#   test:
#     runs-on: ubuntu-latest
#     needs: deploy
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4.1.5
#       - name: install
#         run: npm install
#       - name: run test
#         run: npm run cy:ci:run
#       - name: upload html report
#         if: always()
#         uses: actions/upload-pages-artifact@v3.0.1
#         with:
#           name: test-results
#           path: "cypress/results"
#   go-release:
#     runs-on: ubunto-latest
#     needs: test
#     steps:
#       - name: launch release
#         run: echo "launch release"
#   notify-failure:
#     runs-on: ubunto-latest
#     needs: test
#     /: failure()
#     steps:
#       - name: notify failure
#         run: echo "notify failure"
