name: test and deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "."
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: install
        run: npm install
      - name: run test
        run: npm run cy:ci:run
      - name: upload html report
        if: always()
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: test-results
          path: "cypress/results"
